"""empty message

Revision ID: 3acfbc8099d9
Revises: c11b1493f99e
Create Date: 2019-10-14 11:32:37.887606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3acfbc8099d9'
down_revision = 'c11b1493f99e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('compulsory_purchase_order', 'pdf_filename')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('compulsory_purchase_order', sa.Column('pdf_filename', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
