"""empty message

Revision ID: 739e8ff4e7de
Revises: 3acfbc8099d9
Create Date: 2019-10-14 11:33:10.047684

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '739e8ff4e7de'
down_revision = '3acfbc8099d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('compulsory_purchase_order', sa.Column('pdf_filenames', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('compulsory_purchase_order', 'pdf_filenames')
    # ### end Alembic commands ###
