"""empty message

Revision ID: b09a400ed2c6
Revises: 
Create Date: 2019-08-08 15:31:16.201674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b09a400ed2c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compulsory_purchase_order',
    sa.Column('compulsory_purchase_order', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('organisation', sa.String(), nullable=True),
    sa.Column('compulsory_purchase_order_type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('legislation', sa.String(), nullable=True),
    sa.Column('legislation_name', sa.String(), nullable=True),
    sa.Column('legislation_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('compulsory_purchase_order')
    )
    op.create_table('compulsory_purchase_order_investigation',
    sa.Column('compulsory_purchase_order_investigation', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('inspector_report_url', sa.String(), nullable=True),
    sa.Column('decision_url', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('compulsory_purchase_order_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['compulsory_purchase_order_id'], ['compulsory_purchase_order.compulsory_purchase_order'], ),
    sa.PrimaryKeyConstraint('compulsory_purchase_order_investigation')
    )
    op.create_table('compulsory_purchase_order_status',
    sa.Column('compulsory_purchase_order_status', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('document_url', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('compulsory_purchase_order_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['compulsory_purchase_order_id'], ['compulsory_purchase_order.compulsory_purchase_order'], ),
    sa.PrimaryKeyConstraint('compulsory_purchase_order_status')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('compulsory_purchase_order_status')
    op.drop_table('compulsory_purchase_order_investigation')
    op.drop_table('compulsory_purchase_order')
    # ### end Alembic commands ###
